# Generated by Django 5.1.3 on 2024-11-29 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.PositiveIntegerField()),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(help_text='somente números', max_length=11)),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('SP', 'São Paulo'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('ES', 'Espirito Santo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('GO', 'Goiás'), ('DF', 'Distrito Federal'), ('AC', 'Acre'), ('AM', 'Amazonas'), ('AP', 'Amapa'), ('PA', 'Para'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('TO', 'Tocantins'), ('AL', 'Alagoas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('MA', 'Maranhão'), ('PI', 'Piauí'), ('RN', 'Rio Grande do Norte'), ('SE', 'Sergipe'), ('PB', 'Paraíba'), ('PE', 'Pernambuco')], default='SP', max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
